controllers_front:
    resource: ../../src/Controller/front
    type: annotation


controllers_back:
    resource: ../../src/Controller/back
    type: annotation
    prefix: /admin
    name_prefix: admin_

controllers:
    resource: ../../src/Controller
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
